<section class="game-card garden-game" data-coding-game="{{ json_encode($game, JSON_THROW_ON_ERROR) }}" @if(isset($completionUrl) || isset($module)) data-completion-url="{{ $completionUrl ?? route('play.game', $module) }}" @endif tabindex="0" aria-label="{{ $game['title'] }} coding game. When this game is focused, arrow keys add moves; Enter runs your program.">
    <div class="game-heading"><div><span class="game-kicker">COMMAND GARDEN</span><h2>{{ $game['title'] }}</h2></div><span class="game-badge">{{ isset($completionUrl) || isset($module) ? 'SAVED PLAY' : 'LOCAL PRACTICE' }}</span></div>
    <div class="garden-workbench">
    <div class="game-world">
        <div class="world-label"><span class="world-mission"><span aria-hidden="true">⚑</span> Reach the flag</span><span data-game-objectives>{{ count($game['crystals']) }} crystals left</span></div>
        <div class="game-board" data-game-board role="img" aria-label="Garden with {{ $game['width'] }} columns and {{ $game['height'] }} rows. Start: column {{ $game['start'][0] + 1 }}, row {{ $game['start'][1] + 1 }}. Goal: column {{ $game['goal'][0] + 1 }}, row {{ $game['goal'][1] + 1 }}. Path coordinates: {{ implode('; ', array_map(fn($p) => ($p[0] + 1).','.($p[1] + 1), $game['path'])) }}. Crystal coordinates: {{ implode('; ', array_map(fn($p) => ($p[0] + 1).','.($p[1] + 1), $game['crystals'])) ?: 'none' }}."></div>
        <div class="board-legend"><span><i class="legend-kody" aria-hidden="true"></i>Your explorer</span><span><i class="legend-path" aria-hidden="true"></i>Follow the path</span><span><i class="legend-goal" aria-hidden="true"></i>Goal</span></div>
    </div>
    <div class="game-controls"><div class="game-instructions"><span class="step-pill">{{ $game['concept'] }}</span><p>{{ $game['instructions'] }}</p></div>
        <div class="command-buttons" aria-label="Add movement instructions"><button type="button" data-command="up" aria-label="Add up">↑</button><button type="button" data-command="left" aria-label="Add left">←</button><button type="button" data-command="down" aria-label="Add down">↓</button><button type="button" data-command="right" aria-label="Add right">→</button><button class="undo-command" type="button" data-game-undo aria-label="Remove last instruction">Undo</button></div>
        @if($game['mode'] === 'loop' || ($designerShell ?? false))<label class="game-option"><input type="checkbox" data-game-repeat> Repeat my instructions 2 times</label>@endif
        @if($game['mode'] === 'conditional' || ($designerShell ?? false))<label class="game-option"><input type="checkbox" data-game-conditional> If there’s a crystal, collect it after moving</label>@endif
        <div class="program-heading"><b>Your program</b><span data-game-progress>0 / {{ $game['maxCommands'] }} instructions</span></div>
        <div class="program-track" data-game-program role="group" aria-label="Your program"><span>Add an arrow to start your program</span></div>
        <div class="program-edit-tools"><button type="button" class="game-reset" data-step-earlier disabled aria-label="Move selected instruction earlier">← Earlier</button><button type="button" class="game-reset" data-step-later disabled aria-label="Move selected instruction later">Later →</button><button type="button" class="game-reset" data-step-remove disabled>Remove selected</button></div>
        <div class="game-toolbar"><button class="button button-play" type="button" data-game-run>Run my code <span aria-hidden="true">▶︎</span></button><button type="button" class="game-reset" data-game-reset>Start over</button><button type="button" class="game-reset" data-game-hint>Hint</button></div>
        <p class="game-feedback" data-game-feedback role="status" aria-live="polite">Small steps count. You can try as many times as you like.</p>
        <details class="game-help"><summary>Keyboard & tips</summary><p>Focus the game card, then use arrow keys to add moves and Enter to run. Select a program tile to move or remove it. On a selected tile, Alt + Left/Right moves it and Delete removes it.</p></details>
        <div class="game-success" data-game-success hidden><p><b>You made that happen! ✦</b><span>{{ $game['learningIdea'] }}</span></p>@if(isset($module))<a href="{{ route('dashboard') }}" class="quiet-link">Continue playing →</a>@elseif($trial ?? false)@auth<a href="{{ route('dashboard') }}" class="quiet-link">Continue your saved trail →</a>@else<p>This trial stays here. Create an account to start saving your wins.</p><a href="{{ route('register') }}" class="quiet-link">Start your saved adventure →</a><a href="{{ route('login') }}" class="quiet-link">Already joined? Sign in →</a>@endauth@else<a href="{{ route('learning.catalog') }}" class="quiet-link">Explore your next adventure →</a>@endif</div>
        <noscript><p class="game-feedback">Turn on JavaScript to play. You can still browse modules and create an account.</p></noscript>
    </div>
    </div>
</section>
