@extends('layouts.learning')
@section('title', 'Financial review — Kody')
@section('content')
<section class="review-page page-width"><p class="overline">ADMINISTRATOR FINANCE</p><h1>Review with a clear trail.</h1>
@if(session('status'))<p class="lesson-note" role="status">{{ session('status') }}</p>@endif
@if($errors->any())<p class="studio-errors" role="alert">{{ $errors->first() }}</p>@endif
<p class="lesson-note">Platform cash: PHP {{ \App\Support\ExactMoney::decimal($cash->platform_minor) }} · Reserved: PHP {{ \App\Support\ExactMoney::decimal($cash->reserved_minor) }}. Held margins and recipient earnings are excluded from reward funding.</p>
<div class="dashboard-grid"><article class="lesson-note"><h2>Wallet liabilities</h2><p>PHP {{ \App\Support\ExactMoney::decimal($summary['wallet_backing']) }} backing current wallet lots.</p></article><article class="lesson-note"><h2>Creator liabilities</h2><p>PHP {{ \App\Support\ExactMoney::decimal($summary['unclaimed_creator']) }} allocated, including immature and reserved earnings.</p></article><article class="lesson-note"><h2>Verified purchases</h2><p>PHP {{ \App\Support\ExactMoney::decimal($summary['confirmed_purchases']) }} retained gross receipts; PHP {{ \App\Support\ExactMoney::decimal($summary['confirmed_refunds']) }} fully refunded.</p></article></div>
<details class="lesson-note"><summary>Platform cash ledger</summary><p>Wallet backing and creator earnings are separate liabilities. These entries show platform allocations, reward backing, funding, refunds and actual expenses.</p>@foreach($cashHistory as $entry)<p>{{ $entry->created_at }} · {{ $entry->reference }} · PHP {{ \App\Support\ExactMoney::decimal($entry->amount_minor) }}</p>@endforeach{{ $cashHistory->links() }}</details>
<h2>Payouts</h2><div class="review-list">@forelse($payouts as $row)<a href="{{ route('finance.show', ['payout', $row->id]) }}"><b>PHP {{ \App\Support\ExactMoney::decimal($row->gross_minor) }} · {{ $row->state }}</b><span>Account #{{ $row->user_id }} · {{ $row->id }}</span></a>@empty<p>No payouts need review.</p>@endforelse</div>{{ $payouts->links() }}
<h2>Refunds</h2><div class="review-list">@forelse($refunds as $row)<a href="{{ route('finance.show', ['refund', $row->id]) }}"><b>{{ $row->kind }} · {{ $row->state }}</b><span>Account #{{ $row->user_id }} · {{ $row->id }}</span></a>@empty<p>No refunds need review.</p>@endforelse</div>{{ $refunds->links() }}
<details class="lesson-note"><summary>Record deposited platform funding</summary><p>Use the actual deposit statement reference and evidence. This records platform cash only. It cannot credit player KodeBits or mark provider transactions successful.</p><form class="studio-form" method="post" action="{{ route('finance.fund') }}">@csrf<label>PHP deposited<input name="amount" required inputmode="decimal" maxlength="11"></label><label>Unique statement reference<input name="reference" required maxlength="100"></label><label>Evidence reference<textarea name="evidence" required maxlength="500"></textarea></label>@include('transactions.password-confirmation')<button class="button button-dark">Record attested deposit</button></form></details>
<details class="lesson-note"><summary>Record an actual operating expense</summary><p>Use the settled invoice reference. This reduces reward backing, using only matured, unreserved platform cash. Record monthly budget estimates separately.</p><form class="studio-form" method="post" action="{{ route('finance.expense') }}">@csrf<label>PHP paid<input name="amount" required inputmode="decimal" maxlength="11"></label><label>Unique invoice reference<input name="reference" required maxlength="100"></label><label>Evidence reference<textarea name="evidence" required maxlength="500"></textarea></label>@include('transactions.password-confirmation')<button class="button button-dark">Record paid expense</button></form></details>
<details class="lesson-note"><summary>Report current monthly operating costs</summary><p>Planning ceiling PHP12,000. Include AWS, Judge0, email, gateway minimum/processing and taxes. Report actual invoices plus estimates of remaining committed usage; this is an operator report, not a live cloud billing feed.</p><form class="studio-form" method="post" action="{{ route('finance.budget') }}">@csrf<input type="hidden" name="record_version" value="{{ $budget?->record_version ?? 0 }}"><label>Current monthly PHP cost<input name="amount" required inputmode="decimal" value="{{ $budget ? \App\Support\ExactMoney::decimal($budget->reported_minor) : '' }}" maxlength="11"></label><label>Invoice/estimate sources<textarea name="source" required maxlength="500"></textarea></label>@include('transactions.password-confirmation')<button class="button button-dark">Update cost report</button></form></details>
<h2>Exceptional remedies</h2>@forelse($remedies as $case)<details class="lesson-note"><summary>{{ $case->reference }} · Account #{{ $case->user_id }} · {{ $case->state }}</summary><p>{{ $case->message }}</p><form class="studio-form" method="post" action="{{ route('finance.remedy-review', $case->id) }}">@csrf<label>Decision<select name="state"><option value="Review">Under review</option><option value="Resolved">Resolved</option></select></label><label>Investigation and verified remedy references<textarea name="review_notes" required maxlength="1000"></textarea></label>@include('transactions.password-confirmation')<button class="button button-dark">Record case decision</button></form></details>@empty<p>No exceptional remedy cases.</p>@endforelse{{ $remedies->links() }}
<h2>Provider reconciliation</h2><p class="field-hint">Review mismatched proofs and uncertain provider responses using the operations runbook. Retrying a callback rechecks its existing proof; it does not resend a payment request. There is no browser control to credit a purchase or finalize a payout.</p>@foreach($callbacks as $callback)<details class="lesson-note"><summary>{{ $callback->event }} · {{ $callback->id }}</summary><p>Provider reference: {{ $callback->object_id }}</p><form class="studio-form" method="post" action="{{ route('finance.retry', ['provider', $callback->id]) }}">@csrf<label>Reconciliation evidence<textarea name="notes" required maxlength="500"></textarea></label>@include('transactions.password-confirmation')<button class="button button-dark">Retry proof verification</button></form></details>@endforeach
<h2>Email reconciliation</h2>@foreach($deliveries as $delivery)<details class="lesson-note"><summary>{{ $delivery->title }} · Account #{{ $delivery->user_id }}</summary><p>Delivery {{ $delivery->id }} may already have reached the recipient. Check mail-provider acceptance before retrying; a retry can send a duplicate notice.</p><form class="studio-form" method="post" action="{{ route('finance.retry', ['email', $delivery->id]) }}">@csrf<label>Provider acceptance check<textarea name="notes" required maxlength="500"></textarea></label>@include('transactions.password-confirmation')<button class="button button-dark">Retry this notice</button></form></details>@endforeach
</section>
@endsection
