<?php

use App\Http\Controllers\Account\EmailVerificationController;
use App\Http\Controllers\Account\InstructorApplicationController;
use App\Http\Controllers\Account\InstructorReviewController;
use App\Http\Controllers\Account\LoginController;
use App\Http\Controllers\Account\ProfileController;
use App\Http\Controllers\Account\ProfileEditingController;
use App\Http\Controllers\Account\RecoveryController;
use App\Http\Controllers\Account\RegistrationController;
use App\Http\Controllers\Challenges\ChallengeReviewController;
use App\Http\Controllers\Challenges\ChallengeStudioController;
use App\Http\Controllers\Challenges\ChallengeSubmissionController;
use App\Http\Controllers\Challenges\PublishedChallengeController;
use App\Http\Controllers\Challenges\WeeklyChallengeController;
use App\Http\Controllers\Content\CourseLearningController;
use App\Http\Controllers\Content\CourseReviewController;
use App\Http\Controllers\Content\CourseStudioController;
use App\Http\Controllers\Content\ModuleReviewController;
use App\Http\Controllers\Content\ModuleStudioController;
use App\Http\Controllers\Content\PublishedModuleController;
use App\Http\Controllers\Gamification\WeeklyEventStudioController;
use App\Http\Controllers\LearningController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PlayController;
use Illuminate\Support\Facades\Route;

Route::pattern('course', '[0-9]+');
Route::pattern('challenge', '[0-9]+');
Route::pattern('weeklyEvent', '[0-9]+');

Route::get('/', [LearningController::class, 'home'])->name('home');
Route::get('/learn', [LearningController::class, 'catalog'])->name('learning.catalog');
Route::get('/learn/courses', [CourseLearningController::class, 'catalog'])->name('course-learning.catalog');
Route::get('/challenges', [PublishedChallengeController::class, 'catalog'])->name('challenges.catalog');
Route::middleware(['auth', 'account.session'])->group(function (): void {
    Route::get('/weekly', [WeeklyChallengeController::class, 'index'])->name('weekly-events.index');
    Route::get('/weekly/{weeklyEvent}', [WeeklyChallengeController::class, 'show'])->name('weekly-events.show');
    Route::post('/weekly/{weeklyEvent}/attempts', [WeeklyChallengeController::class, 'store'])->middleware('throttle:10,1,weekly-attempt:')->name('weekly-events.attempt');
    Route::get('/manage/weekly-events', [WeeklyEventStudioController::class, 'index'])->name('weekly-studio.index');
    Route::post('/manage/weekly-events', [WeeklyEventStudioController::class, 'store'])->middleware('throttle:10,1,weekly-configure:')->name('weekly-studio.store');
    Route::get('/challenges/{challenge}', [PublishedChallengeController::class, 'show'])->name('challenges.show');
    Route::post('/challenges/{challenge}/attempts', [ChallengeSubmissionController::class, 'store'])->middleware('throttle:10,1,challenge-attempt:')->name('challenge-attempts.store');
    Route::get('/challenge-attempts/{submission}', [ChallengeSubmissionController::class, 'show'])->whereUuid('submission')->name('challenge-attempts.show');
    Route::get('/challenge-attempts/{submission}/status', [ChallengeSubmissionController::class, 'status'])->whereUuid('submission')->middleware('throttle:90,1,challenge-result:')->name('challenge-attempts.status');
    Route::get('/create/challenges', [ChallengeStudioController::class, 'index'])->name('challenges.index');
    Route::get('/create/challenges/new', [ChallengeStudioController::class, 'create'])->name('challenges.create');
    Route::post('/create/challenges', [ChallengeStudioController::class, 'store'])->middleware('throttle:10,1,challenge-create:')->name('challenges.store');
    Route::get('/create/challenges/{challenge}', [ChallengeStudioController::class, 'edit'])->name('challenges.edit');
    Route::put('/create/challenges/{challenge}', [ChallengeStudioController::class, 'update'])->middleware('throttle:20,1,challenge-edit:')->name('challenges.update');
    Route::post('/create/challenges/{challenge}/submit', [ChallengeStudioController::class, 'submit'])->middleware('throttle:10,1,challenge-submit:')->name('challenges.submit');
    Route::get('/create/challenges/{challenge}/archive', [ChallengeStudioController::class, 'archiveConfirmation'])->name('challenges.archive-confirmation');
    Route::post('/create/challenges/{challenge}/archive', [ChallengeStudioController::class, 'archive'])->middleware('throttle:10,1,challenge-archive:')->name('challenges.archive');
    Route::get('/manage/challenges', [ChallengeReviewController::class, 'index'])->name('challenge-reviews.index');
    Route::get('/manage/challenges/{challenge}', [ChallengeReviewController::class, 'show'])->name('challenge-reviews.show');
    Route::post('/manage/challenges/{challenge}', [ChallengeReviewController::class, 'review'])->middleware('throttle:10,1,challenge-review:')->name('challenge-reviews.review');
    Route::get('/learn/courses/mine', [CourseLearningController::class, 'mine'])->name('course-learning.mine');
    Route::get('/learn/courses/{course}', [CourseLearningController::class, 'show'])->name('course-learning.show');
    Route::post('/learn/courses/{course}/enroll', [CourseLearningController::class, 'enroll'])->middleware('throttle:10,1,course-enroll:')->name('course-learning.enroll');
    Route::get('/learn/courses/{course}/modules/{slot}', [CourseLearningController::class, 'lesson'])->whereNumber('slot')->name('course-learning.lesson');
    Route::post('/learn/courses/{course}/modules/{slot}/game', [CourseLearningController::class, 'game'])->whereNumber('slot')->middleware('throttle:20,1,course-game:')->name('course-learning.game');
    Route::post('/learn/courses/{course}/modules/{slot}/quiz', [CourseLearningController::class, 'quiz'])->whereNumber('slot')->middleware('throttle:20,1,course-quiz:')->name('course-learning.quiz');
    Route::get('/updates', [NotificationController::class, 'index'])->name('notifications.index');
    Route::post('/updates/{notification}/read', [NotificationController::class, 'read'])->whereUuid('notification')->middleware('throttle:30,1,notification-read:')->name('notifications.read');
    Route::get('/learn/modules/{module}', [PublishedModuleController::class, 'show'])->name('modules.show');
    Route::post('/learn/modules/{module}/revisions/{revision}/game', [PublishedModuleController::class, 'game'])->whereNumber('revision')->middleware('throttle:20,1,module-game:')->name('modules.game');
    Route::post('/learn/modules/{module}/revisions/{revision}/quiz', [PublishedModuleController::class, 'quiz'])->whereNumber('revision')->middleware('throttle:20,1,module-quiz:')->name('modules.quiz');
    Route::get('/create', [ModuleStudioController::class, 'index'])->name('studio.index');
    Route::get('/create/courses', [CourseStudioController::class, 'index'])->name('courses.index');
    Route::get('/create/courses/new', [CourseStudioController::class, 'create'])->name('courses.create');
    Route::post('/create/courses', [CourseStudioController::class, 'store'])->middleware('throttle:10,1,course-create:')->name('courses.store');
    Route::get('/create/courses/{course}', [CourseStudioController::class, 'edit'])->name('courses.edit');
    Route::put('/create/courses/{course}', [CourseStudioController::class, 'update'])->middleware('throttle:20,1,course-edit:')->name('courses.update');
    Route::post('/create/courses/{course}/submit', [CourseStudioController::class, 'submit'])->middleware('throttle:10,1,course-submit:')->name('courses.submit');
    Route::get('/create/courses/{course}/archive', [CourseStudioController::class, 'archiveConfirmation'])->name('courses.archive-confirmation');
    Route::post('/create/courses/{course}/archive', [CourseStudioController::class, 'archive'])->middleware('throttle:10,1,course-archive:')->name('courses.archive');
    Route::get('/create/courses/{course}/modules/{slot}', [CourseStudioController::class, 'preview'])->whereNumber('slot')->name('courses.preview');
    Route::get('/manage/courses', [CourseReviewController::class, 'index'])->name('course-reviews.index');
    Route::get('/manage/courses/{course}', [CourseReviewController::class, 'show'])->name('course-reviews.show');
    Route::post('/manage/courses/{course}', [CourseReviewController::class, 'review'])->middleware('throttle:10,1,course-review:')->name('course-reviews.review');
    Route::get('/create/modules/new', [ModuleStudioController::class, 'create'])->name('studio.create');
    Route::post('/create/modules', [ModuleStudioController::class, 'store'])->middleware('throttle:10,1,module-create:')->name('studio.store');
    Route::get('/create/modules/{module}', [ModuleStudioController::class, 'edit'])->name('studio.edit');
    Route::put('/create/modules/{module}', [ModuleStudioController::class, 'update'])->middleware('throttle:20,1,module-edit:')->name('studio.update');
    Route::post('/create/modules/{module}/submit', [ModuleStudioController::class, 'submit'])->middleware('throttle:10,1,module-submit:')->name('studio.submit');
    Route::get('/create/modules/{module}/archive', [ModuleStudioController::class, 'archiveConfirmation'])->name('studio.archive-confirmation');
    Route::post('/create/modules/{module}/archive', [ModuleStudioController::class, 'archive'])->middleware('throttle:10,1,module-archive:')->name('studio.archive');
    Route::get('/manage/modules', [ModuleReviewController::class, 'index'])->name('module-reviews.index');
    Route::get('/manage/modules/{module}', [ModuleReviewController::class, 'show'])->name('module-reviews.show');
    Route::post('/manage/modules/{module}', [ModuleReviewController::class, 'review'])->middleware('throttle:10,1,module-review:')->name('module-reviews.review');
});
Route::get('/learn/{module}', [LearningController::class, 'show'])->middleware(['auth', 'account.session'])->name('learning.show');

Route::middleware('guest')->group(function (): void {
    Route::get('/recover', [RecoveryController::class, 'create'])->name('recovery.request');
    Route::post('/recover', [RecoveryController::class, 'request'])->middleware('throttle:6,1,recovery-email:')->name('recovery.send');
    Route::post('/recover/authorize', [RecoveryController::class, 'authorizeToken'])->middleware('throttle:20,1,recovery-token:')->name('recovery.authorize');
    Route::get('/recover/reset', [RecoveryController::class, 'resetForm'])->name('recovery.reset');
    Route::post('/recover/reset', [RecoveryController::class, 'complete'])->middleware('throttle:10,1,recovery-reset:')->name('recovery.complete');
    Route::get('/login', [LoginController::class, 'create'])->name('login');
    Route::post('/login', [LoginController::class, 'store'])->middleware('throttle:30,1,login:')->name('login.store');
    Route::get('/login/confirmation', [LoginController::class, 'confirmation'])->name('login.confirmation');
    Route::post('/login/confirmation', [LoginController::class, 'confirm'])->middleware('throttle:10,1,login-confirm:')->name('login.confirm');
    Route::get('/register', [RegistrationController::class, 'create'])->name('register');
    Route::post('/register', [RegistrationController::class, 'store'])->middleware('throttle:6,1')->name('register.store');
    Route::get('/email/verify', [EmailVerificationController::class, 'notice'])->name('verification.notice');
    Route::post('/email/verification-link', [EmailVerificationController::class, 'resend'])->middleware('throttle:6,1')->name('verification.resend');
});
Route::post('/email/verify', [EmailVerificationController::class, 'verify'])->middleware('throttle:30,1')->name('verification.verify');
Route::get('/dashboard', [PlayController::class, 'hub'])->middleware(['auth', 'account.session'])->name('dashboard');
Route::post('/play/{level}/game', [PlayController::class, 'game'])->middleware(['auth', 'account.session', 'throttle:20,1,play-game:'])->name('play.game');
Route::post('/play/{level}/quiz', [PlayController::class, 'quiz'])->middleware(['auth', 'account.session', 'throttle:20,1,play-quiz:'])->name('play.quiz');
Route::get('/account', ProfileController::class)->middleware(['auth', 'account.session'])->name('account.show');
Route::get('/account/edit', [ProfileEditingController::class, 'edit'])->middleware(['auth', 'account.session'])->name('account.edit');
Route::get('/account/creator-application', [InstructorApplicationController::class, 'create'])->middleware(['auth', 'account.session'])->name('instructor-application.create');
Route::post('/account/creator-application', [InstructorApplicationController::class, 'store'])->middleware(['auth', 'account.session', 'throttle:5,1,creator-apply:'])->name('instructor-application.store');
Route::patch('/account', [ProfileEditingController::class, 'update'])->middleware(['auth', 'account.session', 'throttle:10,1,profile-edit:'])->name('account.update');
Route::post('/logout', [LoginController::class, 'destroy'])->middleware('auth')->name('logout');
Route::middleware(['auth', 'account.session'])->prefix('manage/instructors')->name('instructor-reviews.')->group(function (): void {
    Route::get('/', [InstructorReviewController::class, 'index'])->name('index');
    Route::get('/{application}', [InstructorReviewController::class, 'show'])->name('show');
    Route::get('/{application}/credential', [InstructorReviewController::class, 'credential'])->middleware('throttle:20,1,credential-read:')->name('credential');
    Route::post('/{application}', [InstructorReviewController::class, 'review'])->middleware('throttle:10,1,creator-review:')->name('review');
});
