@extends('layouts.learning')
@section('title', 'Coding quests — Kody')
@section('content')
<section class="module-section page-width"><p class="overline">A LITTLE PROBLEM. A NEW POSSIBILITY.</p><h1>Find a quest worth solving.</h1><p>Browse reviewed programming problems. Choose a quest to explore its examples and participation options.</p><form method="get" class="catalog-search catalog-filter-panel" action="{{ route('challenges.catalog') }}">
    <div class="filter-search"><label for="challenge-search">Find a coding quest</label><input id="challenge-search" name="q" type="search" maxlength="80" value="{{ $query }}" placeholder="Search a title or programming idea"></div>
    <div class="filter-grid">
        <div><label for="challenge-language">Language</label><select id="challenge-language" name="language"><option value="">All languages</option>@foreach(config('challenges.languages') as $key => $label)<option value="{{ $key }}" @selected(($filters['language'] ?? null) === $key)>{{ $label }}</option>@endforeach</select></div>
        <div><label for="challenge-difficulty">Difficulty</label><select id="challenge-difficulty" name="difficulty"><option value="">All difficulties</option>@foreach(['Easy','Medium','Hard'] as $difficulty)<option @selected(($filters['difficulty'] ?? null) === $difficulty)>{{ $difficulty }}</option>@endforeach</select></div>
        <div><label for="challenge-category">Topic</label><select id="challenge-category" name="category"><option value="">All topics</option>@foreach(config('challenges.categories') as $key => $label)<option value="{{ $key }}" @selected(($filters['category'] ?? null) === $key)>{{ $label }}</option>@endforeach</select></div>
        <div><label for="challenge-tag">Concept</label><select id="challenge-tag" name="tag"><option value="">All concepts</option>@foreach(config('challenges.tags') as $key => $label)<option value="{{ $key }}" @selected(($filters['tag'] ?? null) === $key)>{{ $label }}</option>@endforeach</select></div>
    </div>
    <div class="filter-actions"><button class="button button-dark button-small" type="submit">Search</button>@if($query !== '' || array_filter($filters))<a class="quiet-link" href="{{ route('challenges.catalog') }}">Clear filters</a>@endif<span class="filter-summary">{{ $challenges->total() }} {{ $challenges->total() === 1 ? 'quest' : 'quests' }} found</span></div>
</form>
<div class="module-grid">@forelse($challenges as $revision)<a class="module-card peach" href="{{ route('challenges.show', $revision->challenge_id) }}"><div class="module-art" aria-hidden="true"><span class="module-symbol">{ }</span></div><div class="module-copy"><div class="module-meta"><span>{{ config('challenges.languages.'.$revision->language) }}</span><span>{{ $revision->difficulty }}</span></div><h2>{{ $revision->title }}</h2><p>{{ config('challenges.categories.'.$revision->category) }}</p>@if($revision->tags)<p class="field-hint">@foreach($revision->tags as $tag){{ config('challenges.tags.'.$tag) }}@unless($loop->last) · @endunless @endforeach</p>@endif<p class="content-price">{{ $revision->challenge->creator?->account_status === \App\Enums\AccountStatus::Deleted ? 'Free · retained creator content' : ($revision->price_kb ? $revision->price_kb.' KB' : 'Free') }}@if($revision->minimum_xp > 0) · {{ $revision->minimum_xp }} XP to unlock
@endif</p><span class="module-link">@auth Explore this quest @else Sign in to explore @endauth →</span></div></a>@empty<p class="empty-catalog">No quests match yet. <a href="{{ route('learning.catalog') }}">Try a learning adventure.</a></p>@endforelse</div>{{ $challenges->links() }}</section>
@endsection
