@extends('layouts.learning')
@section('title', 'Challenge studio — Kody')
@section('content')

<section class="review-page page-width">
<div class="studio-heading"><div><p class="overline">CODING QUEST WORKSPACE</p><h1>Make a little coding quest.</h1><p>Start with a clear problem. Add examples and hidden checks, then send your quest for review.</p></div><a class="button button-play" href="{{ route('challenges.create') }}">Create a challenge +</a></div>
<nav class="studio-wayfinding" aria-label="Challenge tools"><a href="{{ route('challenges.catalog') }}">Explore published challenges →</a>@can('create', \App\Models\LearningModule::class)<a href="{{ route('studio.index') }}">Your learning adventures →</a>@endcan</nav>
<section class="studio-library" aria-labelledby="quest-library-heading"><div class="section-heading"><h2 id="quest-library-heading">Your quests</h2><span class="status-pill">{{ $challenges->total() }} {{ $challenges->total() === 1 ? 'quest' : 'quests' }}</span></div><div class="review-list">@forelse($challenges as $challenge)<a href="{{ route('challenges.edit', $challenge) }}"><b>{{ $challenge->latestRevision->title }}</b><span>{{ $challenge->status }} · Revision {{ $challenge->latestRevision->number }} · {{ $challenge->latestRevision->review_status }}</span><span class="quiet-link">Open draft →</span></a>@empty<div class="empty-state"><h3>Your first quest starts with a problem worth solving.</h3><p>Build from an original beginner example below, then customize its tests before submitting for review.</p></div>@endforelse</div>{{ $challenges->links() }}</section>
<details class="starter-library"><summary>Start with a beginner quest.</summary><p>Original problems with sample and hidden edge cases. Customize before saving; opening an example never publishes it.</p><div class="starter-grid">@foreach(config('challenge-examples') as $slug => $example)<article class="starter-card"><h3>{{ $example['title'] }}</h3><p>Use a complete problem and test set in your chosen language.</p>@foreach(config('challenges.languages') as $language => $label)<p><a class="quiet-link" href="{{ route('challenges.create', ['example' => $slug, 'language' => $language]) }}">Use {{ $label }} example →</a></p>@endforeach</article>@endforeach</div></details>
</section>
@endsection
