<?php

return [
    'welcome-code' => ['assessment_kind' => 'none', 'title' => 'What is a program?', 'description' => 'A gentle first lesson for people who have never written code.',
        'content' => "A program is a set of instructions that a computer follows. Think of a recipe: each step says what to do, and the order matters. Computers need clear instructions rather than guesses.\n\nTry this away from the screen: describe how to move from your door to your chair using one small action per step. Which details would a robot need?\n\nIn the next adventures, you will guide a robot. Plan a few steps, run them and compare the result with your prediction. Getting an unexpected result is useful information: change one instruction and try again.\n\nYour goal: explain a program as a sequence of precise instructions. When you are ready, mark this lesson as read."],
    'data-introduction' => ['assessment_kind' => 'none', 'title' => 'Meet the data your code uses', 'description' => 'Connect values, positions and files to familiar objects.',
        'content' => "Programs work with data: a number, a color, a list or a message. A variable is a named place to keep a value, like a labeled box. An array keeps several values in ordered positions. A file keeps content under a name.\n\nA coordinate names a position on a grid. In Kody Pixel Studio, column and row positions start at 1. Some programming languages use 0 for their first array position; always check the convention for the tool you use.\n\nIn Number Machine, every command updates the same stored number. In Sort Lab, a swap changes two positions in a list. In Terminal Quest, commands inspect and copy virtual file content.\n\nYour goal: identify the value an instruction changes, and predict the result before running it. Mark this introduction as read, then explore the four tools."],
    'programming-check' => ['template' => 'choice-quiz', 'title' => 'Connect your first coding ideas', 'description' => 'Practice three ideas: sequence, loop and condition.',
        'content' => 'A sequence follows instructions in order. A loop repeats a pattern. A condition decides whether an action should happen. Think about which tool fits each situation, then use the feedback to explain your reasoning.',
        'quiz_questions' => [
            ['id' => 'sequence', 'question' => 'What can happen if you turn before moving instead of moving before turning?', 'options' => [['id' => 'same', 'label' => 'The result must always stay the same'], ['id' => 'different', 'label' => 'The robot may end up somewhere different'], ['id' => 'stopped', 'label' => 'Every program stops immediately']], 'answer' => 'different', 'explanation' => 'Moving after a turn can send the robot in a different direction. Instruction order changes behavior.'],
            ['id' => 'loop', 'question' => 'You need the same three steps twice. What expresses that repeated pattern?', 'options' => [['id' => 'repeat', 'label' => 'A loop around the three steps'], ['id' => 'rename', 'label' => 'Renaming the robot']], 'answer' => 'repeat', 'explanation' => 'A loop repeats its body. Repeating three steps twice runs six steps in total.'],
            ['id' => 'condition', 'question' => 'Collect a crystal only when one is on the current tile. Which idea fits?', 'options' => [['id' => 'always', 'label' => 'Always collect without checking'], ['id' => 'condition', 'label' => 'Check a condition before collecting']], 'answer' => 'condition', 'explanation' => 'A condition checks whether the crystal is present. The action happens only when the check is true.'],
        ]],
    'data-check' => ['template' => 'choice-quiz', 'title' => 'Connect values lists and files', 'description' => 'Check what changes in each of your four data adventures.',
        'content' => 'Coordinates locate a cell. Arithmetic updates a stored value. Sorting changes the order of a list. Terminal commands inspect or copy named files. Revisit a tool if you want to test an idea before answering.',
        'quiz_questions' => [
            ['id' => 'number', 'question' => 'Start with 2, add 3, then multiply by 2. What value is stored?', 'options' => [['id' => 'seven', 'label' => '7'], ['id' => 'ten', 'label' => '10'], ['id' => 'twelve', 'label' => '12']], 'answer' => 'ten', 'explanation' => 'First 2 + 3 becomes 5. Multiplying that updated value by 2 gives 10.'],
            ['id' => 'list', 'question' => 'What does swapping two positions in a list change?', 'options' => [['id' => 'order', 'label' => 'The positions of two values'], ['id' => 'values', 'label' => 'The numeric values themselves']], 'answer' => 'order', 'explanation' => 'Swapping moves values to different positions. It preserves the values and the length of the list.'],
            ['id' => 'terminal', 'question' => 'After copying a message to a new file, how can you inspect its contents?', 'options' => [['id' => 'list', 'label' => 'Use ls to read its whole content'], ['id' => 'read', 'label' => 'Use cat with the destination filename']], 'answer' => 'read', 'explanation' => 'ls lists filenames; cat reads a named file. Kody Terminal Quest uses a virtual filesystem.'],
        ]],
    'sequences' => ['title' => 'A robot takes its first steps', 'description' => 'Teach instruction order with a tiny garden journey.', 'content' => "A sequence runs one instruction after another. Changing the order can change where you end up.\n\nPlan a path to the flag. Run your instructions, notice where the robot goes, then change one step and try again."],
    'loops' => ['title' => 'Spot the repeating trail', 'description' => 'Help learners replace repeated steps with one pattern.', 'content' => "A loop repeats a set of instructions. Look for a short pattern that appears twice along the trail.\n\nBuild the pattern, enable repeat, then run it. How many instructions did the loop save you?"],
    'conditions' => ['title' => 'A robot makes a choice', 'description' => 'Explore conditions by collecting crystals along a path.', 'content' => "A condition checks whether something is true before taking an action. The crystal rule collects only when a crystal is present.\n\nTry the path without the rule, then with it. Explain what changes on a tile with no crystal."],
    'pixel-studio' => ['title' => 'Paint a tiny picture with code', 'description' => 'Use coordinates and colors to recreate a pixel picture.', 'content' => "Coordinates tell a program where to act. In this canvas, the first number is the column and the second is the row, starting at 1.\n\nUse paint 1 1 mint to color the top-left cell. Match the target picture exactly, leaving other cells blank. Try a different coordinate and see what moves."],
    'number-machine' => ['title' => 'Transform a number', 'description' => 'Discover how instructions change the value stored in a machine.', 'content' => "A variable holds a value that instructions can change. This machine starts with a number; each command updates that same value.\n\nTry add 3, then multiply 2. Would reversing those instructions give the same result? Reach the target and describe your steps."],
    'sort-lab' => ['title' => 'Put a list in order', 'description' => 'Compare values and swap positions to sort a small list.', 'content' => "A list stores values in positions. Sorting puts them in a chosen order. Compare neighboring values and swap those that are out of order.\n\nUse swap 1 2 to exchange the first two positions. Keep comparing until the entire list goes from smallest to largest."],
    'terminal-quest' => ['title' => 'Deliver a message in the terminal', 'description' => 'Practice listing, reading and copying virtual files.', 'content' => "A terminal lets you give instructions as text. This practice world has virtual files: ls lists them, cat reads one, and cp copies one to a new name.\n\nInspect the files, find the required message, copy it to the destination, then read the destination to check your work. These commands affect only this game's virtual world."],
    'choice-quiz' => ['title' => 'Check your sequence intuition', 'description' => 'A two-choice practice check with useful feedback.', 'content' => 'Programs follow instructions in order. Think about moving one step and then turning: turning first can send you somewhere else. Use the question below to explain why order matters.'],
];
