<?php

return [
    'sequences' => ['title' => 'A robot takes its first steps', 'description' => 'Teach instruction order with a tiny garden journey.', 'content' => "A sequence runs one instruction after another. Changing the order can change where you end up.\n\nPlan a path to the flag. Run your instructions, notice where the robot goes, then change one step and try again."],
    'loops' => ['title' => 'Spot the repeating trail', 'description' => 'Help learners replace repeated steps with one pattern.', 'content' => "A loop repeats a set of instructions. Look for a short pattern that appears twice along the trail.\n\nBuild the pattern, enable repeat, then run it. How many instructions did the loop save you?"],
    'conditions' => ['title' => 'A robot makes a choice', 'description' => 'Explore conditions by collecting crystals along a path.', 'content' => "A condition checks whether something is true before taking an action. The crystal rule collects only when a crystal is present.\n\nTry the path without the rule, then with it. Explain what changes on a tile with no crystal."],
    'pixel-studio' => ['title' => 'Paint a tiny picture with code', 'description' => 'Use coordinates and colors to recreate a pixel picture.', 'content' => "Coordinates tell a program where to act. In this canvas, the first number is the column and the second is the row, starting at 1.\n\nUse paint 1 1 mint to color the top-left cell. Match the target picture exactly, leaving other cells blank. Try a different coordinate and see what moves."],
    'number-machine' => ['title' => 'Transform a number', 'description' => 'Discover how instructions change the value stored in a machine.', 'content' => "A variable holds a value that instructions can change. This machine starts with a number; each command updates that same value.\n\nTry add 3, then multiply 2. Would reversing those instructions give the same result? Reach the target and describe your steps."],
    'sort-lab' => ['title' => 'Put a list in order', 'description' => 'Compare values and swap positions to sort a small list.', 'content' => "A list stores values in positions. Sorting puts them in a chosen order. Compare neighboring values and swap those that are out of order.\n\nUse swap 1 2 to exchange the first two positions. Keep comparing until the entire list goes from smallest to largest."],
    'terminal-quest' => ['title' => 'Deliver a message in the terminal', 'description' => 'Practice listing, reading and copying virtual files.', 'content' => "A terminal lets you give instructions as text. This practice world has virtual files: ls lists them, cat reads one, and cp copies one to a new name.\n\nInspect the files, find the required message, copy it to the destination, then read the destination to check your work. These commands affect only this game's virtual world."],
    'choice-quiz' => ['title' => 'Check your sequence intuition', 'description' => 'A two-choice practice check with useful feedback.', 'content' => 'Programs follow instructions in order. Think about moving one step and then turning: turning first can send you somewhere else. Use the question below to explain why order matters.'],
];
